[package]
name = "cli_graph_crate"
version = "0.1.0"
authors = ["jcawl <jcawl123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piechart = "1.0.0"
fastrand = "1.5.0"